"""password hashing

Revision ID: 0f3f21bb0579
Revises: 3e7242bdffab
Create Date: 2022-04-29 18:14:57.228410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f3f21bb0579'
down_revision = '3e7242bdffab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernames', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.alter_column('usernames', 'location',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usernames', 'location',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.drop_column('usernames', 'password_hash')
    # ### end Alembic commands ###
