"""Initial Migration

Revision ID: 3e7242bdffab
Revises: 
Create Date: 2022-04-29 14:32:59.976976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7242bdffab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usernames', sa.Column('location', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usernames', 'location')
    # ### end Alembic commands ###
